# Copyright (c) 2022 PHPER Framework Team
# PHPER is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan
# PSL v2. You may obtain a copy of Mulan PSL v2 at:
#          http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY
# KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
# NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

header:
  license:
    spdx-id: MulanPSL-2.0
    copyright-owner: PHPER Framework Team
    software-name: PHPER

  paths-ignore:
    - 'LICENSE'
    - 'NOTICE'
    - '**/*.md'
    - '**/*.lock'
    - '**/.gitignore'
    - '**/.gitmodules'
    - 'vendor'
    - '.cargo'
    - '.vscode'
    - '.idea'

  comment: on-failure

dependency:
  files:
    - Cargo.toml
